on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install CI dependencies
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y texlive texlive-fonts-extra
      - name: Build
        run: |
          ./build.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public  # replace with your actual output folder
